# Generated by Django 5.2.13 on 2026-05-02 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('gender', models.CharField(blank=True, choices=[('m', 'мужской'), ('f', 'женский'), ('', 'не указан')], default='', max_length=1, verbose_name='пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='день рождения')),
                ('marital_status', models.CharField(blank=True, choices=[('', 'не указано'), ('single', 'не женат / не замужем'), ('relationship', 'встречается'), ('engaged', 'помолвлен(а)'), ('married', 'женат / замужем'), ('complicated', 'всё сложно'), ('searching', 'в активном поиске'), ('love', 'влюблён(а)')], default='', max_length=20, verbose_name='сем. положение')),
                ('home_city', models.CharField(blank=True, max_length=120, verbose_name='родной город')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='языки')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='деятельность')),
                ('interests', models.TextField(blank=True, verbose_name='интересы')),
                ('favourite_music', models.TextField(blank=True, verbose_name='любимая музыка')),
                ('favourite_movies', models.TextField(blank=True, verbose_name='любимые фильмы')),
                ('favourite_books', models.TextField(blank=True, verbose_name='любимые книги')),
                ('favourite_quotes', models.TextField(blank=True, verbose_name='любимые цитаты')),
                ('about', models.TextField(blank=True, verbose_name='о себе')),
                ('skype', models.CharField(blank=True, max_length=80, verbose_name='Skype')),
                ('icq', models.CharField(blank=True, max_length=20, verbose_name='ICQ')),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
