# Generated by Django 5.2.13 on 2026-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_audio',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мои аудиозаписи'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_groups',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мои группы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_messages',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто может писать мне'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_photos',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мои фотографии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_profile',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мою страницу'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_video',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мои видеозаписи'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_wall_post',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто может писать на стену'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_wall_view',
            field=models.CharField(choices=[('all', 'все'), ('friends', 'только друзья'), ('me', 'только я')], default='all', max_length=10, verbose_name='кто видит мою стену'),
        ),
    ]
