# Generated by Django 5.2.13 on 2026-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, help_text='например: «СПбГУ ’06»', max_length=120, verbose_name='образование'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_games',
            field=models.TextField(blank=True, verbose_name='любимые игры'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_tv',
            field=models.TextField(blank=True, verbose_name='любимые телешоу'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='мобильный телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='political_views',
            field=models.CharField(blank=True, choices=[('', 'не указаны'), ('indifferent', 'безразличные'), ('communist', 'коммунистические'), ('socialist', 'социалистические'), ('moderate', 'умеренные'), ('liberal', 'либеральные'), ('conservative', 'консервативные'), ('monarchist', 'монархические'), ('ultraconservative', 'ультраконсервативные'), ('libertarian', 'либертарианские')], default='', max_length=20, verbose_name='полит. взгляды'),
        ),
        migrations.AddField(
            model_name='profile',
            name='religious_views',
            field=models.CharField(blank=True, max_length=80, verbose_name='религ. взгляды'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, max_length=200, verbose_name='веб-сайт'),
        ),
    ]
