# Generated by Django 5.2.13 on 2026-05-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('profiles', '0004_profile_education_profile_favourite_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='now_playing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='audio.audiotrack'),
        ),
        migrations.AddField(
            model_name='profile',
            name='now_playing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
