# Generated by Django 5.2.13 on 2026-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_now_playing_profile_now_playing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
