# Generated by Django 5.2.13 on 2026-05-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('wall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wallpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('owner__isnull', False)), models.Q(('group__isnull', False), ('owner__isnull', True)), _connector='OR'), name='wallpost_owner_xor_group'),
        ),
    ]
