# Generated by Django 5.2.13 on 2026-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_wallpost_group_alter_wallpost_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='graffiti',
            field=models.ImageField(blank=True, null=True, upload_to='graffiti/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
