# Generated by Django 5.2.13 on 2026-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_wallpost_graffiti_alter_wallpost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wall/%Y/%m/'),
        ),
    ]
