# Generated by Django 5.2.13 on 2026-05-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouplink'),
        ('messaging', '0005_dialog_participants_step3_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='groups.group'),
        ),
    ]
