# Generated by Django 5.2.13 on 2026-05-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='groups.group')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='groups.group')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('group', 'linked')},
            },
        ),
    ]
